# dask-config.yaml

worker:
  replicas: 8
  limits:
    cpu: 2
    memory: 7.5 GiB
  pipPackages: >-
    git+https://github.com/gcsfs/gcsfs.git
    git+https://github.com/xarray/xarray.git
  condaPackages: >-
    -c conda-forge
    zarr
    blosc

jupyter:
  replicas: 0
